#%RAML 1.0
baseUri: https://anypoint.mulesoft.com/mocking/api/v1/links/fd353928-bce8-4550-a88a-a4374d25c831/ # baseUri: http://localhost:8081/
title: Customer management api

traits:
  commons_errors:
    description:  common reource not found errors 
    responses:
      404:
        body:
          application/json:
             example: 
              {"Message":"resource not found"}
  params:
    description:  the client key is required for deleteting action 
    queryParameters:
      ClientKey:
        required: true
        type: string
      
types:
  TestSchema: !include schemas/request_schema.json

/customers:
  post:
    body:
      application/json:
        type: TestSchema
        example: !include examples/resquest.json
    responses:
      201:
        body:
          application/json:
            example: !include examples/success_response.json
      400:
        body:
          application/json:
            example: !include Erorors/post.bad_request.json
  get:
    responses:
      200:
        body:
          application/json:
            example: !include examples/success_response.json
 
        
    is: [commons_errors]
              
  delete:
    is: [params]
    responses:
      200:
        body:
          application/json:
            example: !include examples/delete_succes_response.json
      400:
        body:
          application/json:
            example: !include Erorors/delete_bad_request.json
      204:
        body:
          application/json:
            example: !include Erorors/delete_no_content.json
              
             
      

                        
     
        
    



